"use client";
import Link from "next/link";import { useEffect,useMemo,useState } from "react";import { Clock3, MoreHorizontal, Plus, Video } from "lucide-react";import { api, Meeting } from "../lib/api";import { CreateMeetingModal } from "../components/CreateMeetingModal";
function fmtDate(v:string){return new Intl.DateTimeFormat("en-US",{month:"short",day:"numeric",year:"numeric",hour:"numeric",minute:"2-digit"}).format(new Date(v))}
function duration(s:number){const m=Math.floor(s/60),sec=Math.round(s%60);return `${m}m${sec?` ${sec}s`:""}`}
export default function Home(){const [meetings,setMeetings]=useState<Meeting[]>([]);const [loading,setLoading]=useState(true);const [search,setSearch]=useState("");const [sort,setSort]=useState("recent");const [dateFilter,setDateFilter]=useState("all");const [show,setShow]=useState(false);const [toast,setToast]=useState("");
const load=async()=>{setLoading(true);try{setMeetings(await api.meetings(`?search=${encodeURIComponent(search)}&sort=${sort}`))}catch(e:any){setToast("Backend unavailable. Start FastAPI on port 8000.")}finally{setLoading(false)}};
useEffect(()=>{const fromUrl=new URLSearchParams(window.location.search).get("search");if(fromUrl)setSearch(fromUrl)},[]);useEffect(()=>{load()},[search,sort]);useEffect(()=>{const fn=()=>setShow(true);window.addEventListener("open-create-meeting",fn);return()=>window.removeEventListener("open-create-meeting",fn)},[]);
const deleteMeeting=async(id:number)=>{if(!confirm("Delete this meeting? This cannot be undone."))return;await api.remove(id);setToast("Meeting deleted");load();setTimeout(()=>setToast(""),2500)};
const visibleMeetings=useMemo(()=>meetings.filter(m=>dateFilter==="all"||(Date.now()-new Date(m.date).getTime())<=Number(dateFilter)*86400000),[meetings,dateFilter]);
return <><section className="content"><div className="page-title"><div><h1>Meetings</h1><p>Your meeting library, notes and transcripts in one workspace.</p></div><button className="primary" onClick={()=>setShow(true)}><Plus size={15}/> New meeting</button></div><div className="toolbar"><div className="filters"><div className="search" style={{width:300}}><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search meetings or people..."/></div><select className="select" value={sort} onChange={e=>setSort(e.target.value)}><option value="recent">Most recent</option><option value="oldest">Oldest</option></select><select className="select" value={dateFilter} onChange={e=>setDateFilter(e.target.value)}><option value="all">Any date</option><option value="7">Last 7 days</option><option value="30">Last 30 days</option></select></div><div className="muted" style={{paddingTop:10}}>{visibleMeetings.length} meetings</div></div><div className="table-card"><div className="table-head"><div>Meeting</div><div>Date</div><div>Participants</div><div></div></div>{loading?<div className="empty">Loading meetings...</div>:meetings.length===0?<div className="empty"><div className="empty-icon"><Video size={20}/></div><strong>No meetings found</strong><div style={{marginTop:5}}>Try another search or create your first meeting.</div></div>:visibleMeetings.map(m=><div className="meeting-row" key={m.id}><Link href={`/meetings/${m.id}`} className="meeting-main" style={{textDecoration:"none",color:"inherit"}}><div className="meeting-icon"><Video size={17}/></div><div style={{minWidth:0}}><div className="meeting-name">{m.title}</div><div className="meeting-meta"><Clock3 size={11} style={{verticalAlign:"-2px",marginRight:3}}/>{duration(m.duration)} · {m.transcript.length} transcript segments</div></div></Link><div><div style={{fontSize:12}}>{fmtDate(m.date).split(",")[0]}</div><div className="muted">{fmtDate(m.date).split(",").slice(1).join(",")}</div></div><div className="participants">{m.participants.slice(0,4).map((p,i)=><div className="mini-avatar" key={p.id||i} title={p.name}>{p.name.split(" ").map(x=>x[0]).join("").slice(0,2)}</div>)}{m.participants.length>4&&<span className="muted" style={{marginLeft:8}}>+{m.participants.length-4}</span>}</div><div className="row-menu"><button className="icon-btn" title="Delete" onClick={()=>deleteMeeting(m.id)}><MoreHorizontal size={16}/></button></div></div>)}</div></section>{show&&<CreateMeetingModal onClose={()=>setShow(false)} onCreated={id=>{setShow(false);window.location.href=`/meetings/${id}`}}/>}{toast&&<div className="toast">{toast}</div>}</>}
