"use client";
import { useState } from "react";import { FileText, Upload } from "lucide-react";import { Modal } from "./Modal";import { api } from "../lib/api";
function parseTimestamp(s:string){const p=s.trim().split(":").map(Number);return p.length===2?p[0]*60+p[1]:p.length===3?p[0]*3600+p[1]*60+p[2]:0}
function parseTranscript(raw:string){
  const vttBlocks=raw.replace(/^WEBVTT.*$/m,"").trim().split(/\n\s*\n/).map(x=>x.trim()).filter(Boolean);
  const vtt=vttBlocks.map(block=>{const lines=block.split(/\r?\n/);const idx=lines.findIndex(x=>x.includes("-->") );if(idx<0)return null;const [a,b]=lines[idx].split("-->").map(x=>x.trim().split(/[ .]/)[0]);const text=lines.slice(idx+1).join(" ").trim();return {speaker:"Speaker",start_time:parseTimestamp(a.replace(/,/g,".")),end_time:parseTimestamp(b.replace(/,/g,".")),text}}).filter(Boolean) as any[];
  if(vtt.length)return vtt;
  try{const parsed=JSON.parse(raw);if(Array.isArray(parsed))return parsed.map((x:any)=>({speaker:x.speaker||x.name||"Speaker",start_time:Number(x.start_time??x.start??0),end_time:Number(x.end_time??x.end??(Number(x.start_time??0)+5)),text:String(x.text||x.content||"")}))}catch{}
  return raw.split(/\r?\n/).filter(Boolean).map((line,i)=>{const m=line.match(/^\s*(?:\[?([0-9:.]+)\]?\s+)?([^:]{1,40}):\s*(.*)$/);return {speaker:m?.[2]?.trim()||"Speaker",start_time:m?.[1]?parseTimestamp(m[1]):i*8,end_time:(m?.[1]?parseTimestamp(m[1]):i*8)+8,text:m?.[3]?.trim()||line}});
}
export function CreateMeetingModal({onClose,onCreated}:{onClose:()=>void;onCreated:(id:number)=>void}){const [title,setTitle]=useState("");const [participants,setParticipants]=useState("");const [text,setText]=useState("");const [file,setFile]=useState("");const [busy,setBusy]=useState(false);const [error,setError]=useState("");
const handleFile=async(e:React.ChangeEvent<HTMLInputElement>)=>{const f=e.target.files?.[0];if(!f)return;setFile(f.name);setText(await f.text())};
const create=async()=>{if(!title.trim())return setError("Meeting title is required.");setBusy(true);setError("");try{let transcript=[] as any[];if(text.trim())transcript=parseTranscript(text);const names=participants.split(",").map(x=>x.trim()).filter(Boolean);const duration=transcript.length?Math.ceil(Math.max(...transcript.map(x=>x.end_time))):0;const meeting=await api.create({title:title.trim(),duration,participants:names.map(name=>({name})),transcript,summary:{overview:"Summary will be refined from the meeting transcript.",key_topics:[],outline:[]},action_items:[]});onCreated(meeting.id)}catch(e:any){setError(e.message||"Could not create meeting")}finally{setBusy(false)}};
return <Modal title="Create a meeting" onClose={onClose} footer={<><button className="secondary" onClick={onClose}>Cancel</button><button className="primary" disabled={busy} onClick={create}>{busy?"Creating...":"Create meeting"}</button></>}><div className="field"><label>Meeting title</label><input autoFocus value={title} onChange={e=>setTitle(e.target.value)} placeholder="e.g. Product roadmap sync"/></div><div className="field"><label>Participants <span className="muted">(comma separated)</span></label><input value={participants} onChange={e=>setParticipants(e.target.value)} placeholder="Alex, Sarah, Mike"/></div><div className="field"><label>Transcript</label><textarea value={text} onChange={e=>setText(e.target.value)} placeholder={'Paste transcript lines like:\n00:00 Alex: Welcome everyone.\n00:08 Sarah: Let’s begin...'} /><div className="upload"><label style={{display:"flex",gap:8,alignItems:"center",cursor:"pointer"}}><Upload size={15}/><span>{file||"Upload .txt, .vtt or .json transcript"}</span><input hidden type="file" accept=".txt,.vtt,.json" onChange={handleFile}/></label></div></div>{error&&<div style={{color:"#dc3c3c",fontSize:11}}>{error}</div>}<div className="muted" style={{display:"flex",gap:6,alignItems:"center"}}><FileText size={13}/> Audio transcription is intentionally mocked per the assignment.</div></Modal>}
